name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug Repository Files
        run: ls -la

      - name: Change to Project Directory
        run: cd lab-08_redo

      - name: Install Dependencies
        run: npm install
        working-directory: lab-08_redo

      - name: Run Tests
        run: npm test
        working-directory: lab-08_redo
